import os
import sys
import json
import time
import copy
import logging
import argparse

from PIL import Image
from PyPDF2 import PdfReader, PdfWriter
from pdf2image import convert_from_path
from langchain.docstore.document import Document
from langchain_openai import AzureOpenAIEmbeddings, OpenAIEmbeddings
from langchain_community.vectorstores.azuresearch import AzureSearch
from langchain.text_splitter import TokenTextSplitter, CharacterTextSplitter

from transformers import Pix2StructProcessor, Pix2StructForConditionalGeneration
from src.financialqa.ingestion.models.model_base_decoder import infer_base_decoder

from azure.core.credentials import AzureKeyCredential
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient
from azure.search.documents.indexes import SearchIndexClient
from azure.search.documents.indexes.models import (
    SearchableField,
    SearchField,
    SearchFieldDataType,
    SimpleField,
    VectorSearch,
    HnswParameters,
    VectorSearchProfile,
    VectorSearchAlgorithmKind,
    HnswAlgorithmConfiguration,
    VectorSearchAlgorithmMetric,
)

from dotenv import load_dotenv
load_dotenv(override=True)

from .helper import preprocess_text
from .parser import parse_pdfs, page_pdf_contents

import warnings  # not recommended, to suppress langchain openai error
warnings.filterwarnings("ignore")

'''
To-do's:
    - Load PDFs from blob storage directly before passing to Doc. Intel.
    - Improve assigning to dict in generate_table_from_chart()
'''

class IngestionPipeline:
    """
    A class which provides functionality to extract blob storage container contents,
    construct and chunk financial tabular Document objects, and uploading the documents
    to an Azure AI Search index for use in a Financial-QA RAG application.
    """
    
    def __init__(self):
        self.configure_logging()
        self._load_api_vars()
        self.blob_storage_container = self._get_blob_container_client()
        self.search_client = self._get_search_client()
        self.embedding_model = self._get_embedding_model()

    def configure_logging(self):
        logger = logging.getLogger('azure.core.pipeline.policies.http_logging_policy')  
        logger.setLevel(logging.CRITICAL)
        httpx_logger = logging.getLogger('httpx')  
        httpx_logger.setLevel(logging.WARNING)  # Set the httpx logging level to WARNING to suppress Azure INFO logs
        logging.basicConfig(        
            level=logging.INFO,    
            format="%(asctime)s %(levelname)s %(name)s line %(lineno)d  %(message)s",    
            datefmt="%H:%M:%S",
            force=True,
        )  
        self.logger = logging.getLogger(__name__)  
        self.logger.info('Configured logging')

    def extract_report_contents(self, load_from_local=False):
        """Extract blob reports from Azure Blob Storage container."""
        report_contents = {}
        self.logger.info(
            "Extracting {0} PDF contents from Azure Blob Storage container '{1}'...".\
                format(
                    len(select_files),
                    self.azure_storage_container_name,
                ))
        for blob in self.blob_storage_container.list_blobs():
            if select_files and blob.name not in select_files:
                continue
            report_name = blob.name
            self.logger.info("Extracting contents from file '{0}'.".format(report_name))
            report_blob_path = 'https://' \
                                + os.environ['AZURE_STORAGE_CONTAINER_ACCOUNT'] \
                                + '.blob.core.windows.net/' \
                                + os.environ['AZURE_STORAGE_CONTAINER_NAME'] \
                                + '/' + report_name
            name_contents = report_name.split('_')
            company_name = name_contents[0]
            report_quarter = name_contents[-1].replace('.pdf', '')
            report_contents[report_name] = {
                'company_name': company_name, 
                'report_quarter': report_quarter,
                'report_blob_path': report_blob_path,
            }
        return report_contents
    
    def crop_images_from_pdfs(
            self, 
            pdf_pages_dict, 
            save_as_jpg=False,
        ):
        """
        Crop and save images from PDFs using PyPDF2 with bounding box coordinates
        generated by Azure Document Intelligence.
        """
        for pdf_name, pdf_contents in pdf_pages_dict.items():
            pdf_pages = pdf_contents.get('pages')
            for page_num, page_dict in pdf_pages.items():
                if not 'figures' in page_dict:
                    continue
                print(f'Processing figures on page {page_num} of {pdf_name}...')
                pdf_figures = page_dict.get('figures')
                pdf_file = os.path.join('../data', pdf_name + '.pdf')
                reader = PdfReader(pdf_file)
                page = reader.pages[page_num-1]
                for figure_name, figure_items in pdf_figures.items():
                    bounding_regions_polygon = figure_items.get('bounding_regions_polygon')
                    # found this 72 scaling factor here:
                    # https://github.com/microsoft/Form-Recognizer-Toolkit/blob/main/SampleCode/Python/sample_figure_understanding.ipynb
                    bounding_regions_polygon = [72 * polygon for polygon in bounding_regions_polygon]
                    x1, y1, x2, y2, x3, y3, x4, y4 = bounding_regions_polygon
                    page_mediabox_upper_left = copy.deepcopy(page.mediabox.upper_left)
                    page_mediabox_lower_right = copy.deepcopy(page.mediabox.lower_right)
                    new_upper_left = (
                        page.mediabox.upper_left[0].as_numeric() + x1, 
                        page.mediabox.upper_left[1].as_numeric() - y1
                    )
                    new_upper_right = (
                        page.mediabox.upper_left[0].as_numeric() + x2, 
                        page.mediabox.upper_left[1].as_numeric() - y2
                    )
                    new_lower_right = (
                        page.mediabox.upper_left[0].as_numeric() + x3, 
                        page.mediabox.upper_left[1].as_numeric() - y3
                    )
                    new_lower_left = (
                        page.mediabox.upper_left[0].as_numeric() + x4, 
                        page.mediabox.upper_left[1].as_numeric() - y4
                    )
                    page.mediabox.upper_left = new_upper_left
                    page.mediabox.lower_right = new_lower_right
                    # page.mediabox.upper_right = new_upper_right
                    # page.mediabox.lower_left = new_lower_left
                    writer = PdfWriter() # find a workaround to reinitalizing
                    writer.add_page(page)
                    page.mediabox.upper_left = page_mediabox_upper_left
                    page.mediabox.lower_right = page_mediabox_lower_right
                    output_dir = os.path.join('../data/outputs', pdf_name)
                    if not os.path.isdir(output_dir):
                        print(f"Creating a directory '{output_dir}' to save outputs...")
                        os.makedirs(output_dir)
                    pdf_file_path = os.path.join(output_dir, figure_name + '.pdf')
                    pdf_pages.get(page_num).get('figures').get(figure_name).\
                        update({'pdf_file_path': pdf_file_path})
                    with open(pdf_file_path, 'wb') as out_f:
                        writer.write(out_f)
                    if save_as_jpg:
                        jpg_output_folder = os.path.join(
                            '../data',
                            'outputs', 
                            pdf_name, 
                            'jpg_outputs'
                        )
                        if not os.path.isdir(jpg_output_folder):   
                            print(f"Creating a directory '{jpg_output_folder}' to save JPEG outputs...")
                            os.makedirs(jpg_output_folder)
                        images = convert_from_path(
                            pdf_file_path,
                            fmt='JPEG',
                            output_folder=jpg_output_folder,
                        )
                        jpg_file_path = os.path.join(
                            jpg_output_folder, 
                            figure_name + '.jpg',
                        )
                        pdf_pages.get(page_num).get('figures').get(figure_name).\
                            update({'jpg_file_path': jpg_file_path})
                        for img in images:
                            print(f"Saving PDF '{pdf_name}' as JPEG to folder '{jpg_output_folder}'.")
                            img.save(fp=jpg_file_path)

    def generate_chartvlm_output(
            self,
            model_path,
            image_path,
        ):
        self.logger.info(f'Generating ChartVLM output for figure with JPG path: {image_path}...')
        img = Image.open(image_path).convert("RGB")
        chartvlm_decoder_output = infer_base_decoder(
            img, 
            model_path, 
            title_type=False,
        )
        return chartvlm_decoder_output
    
    def generate_deplot_output(
            self, 
            image_path,
        ):
        pix2struct_processor = Pix2StructProcessor.from_pretrained('google/deplot')
        pix2struct_model = Pix2StructForConditionalGeneration.from_pretrained('google/deplot')
        self.logger.info(f'Generating DePlot output for figure with JPG path: {image_path}...')
        image = Image.open(fp=image_path)
        inputs = pix2struct_processor(
            images=image, 
            text="Generate underlying data table of the figure below:", 
            return_tensors="pt"
        )
        predictions = pix2struct_model.generate(**inputs, max_new_tokens=512)
        deplot_output = pix2struct_processor.decode(
            predictions[0], 
            skip_special_tokens=True
        )
        self.logger.info(f'DePlot output for figure with image path: {image_path}:\n{deplot_output}')
        return deplot_output

    def generate_table_from_chart(
            self,
            pdf_pages_dict,
            chart_model='deplot',
            chart_model_path='',
        ):
        for pdf_name, pdf_items in pdf_pages_dict.items():
            company_name = pdf_items.get('company_name')
            pages = pdf_items.get('pages')
            for page_num, page_content in pages.items():
                if not 'figures' in page_content.keys():
                    continue
                for figure_name, figure_contents in page_content.get('figures').items():
                    image_path = figure_contents.get('jpg_file_path')
                    if chart_model == 'chartvlm':
                        chart_to_table_output = self.generate_chartvlm_output(
                            chart_model_path,
                            image_path,
                        )
                    elif chart_model == 'deplot':
                        chart_to_table_output = self.generate_deplot_output(
                            image_path,
                        )
                    figure_contents.update({'chart_table': chart_to_table_output})

    def convert_paged_pdf_contents_to_docs(
            self, 
            paged_pdf_contents,
            convert_tables=True,
            convert_charts=True,
        ):
        """Create LangChain Document objects from extracted PDF contents."""
        text_docs = []
        table_docs = []
        chart_docs = []
        self.logger.info('Converting extracted PDF page contents to Document objects..')
        for pdf_name, pdf_items in paged_pdf_contents.items():
            company_name = pdf_items.get('company_name')
            report_quarter = pdf_items.get('report_quarter')
            pages = pdf_items.get('pages')
            for page_num, page_content in pages.items():
                # Convert text content by default
                text_content = preprocess_text(' '.join(page_content.get('text')))
                text_docs.append(
                    Document(
                        page_content=text_content,
                        metadata={
                            'page_num': page_num,
                            'pdf_name': pdf_name,
                            'company_name': company_name,
                            'report_quarter': report_quarter,
                            'page_titles': '',
                            'page_headers': '',
                            'section_headers': '',
                            'page_footers': '',
                            # 'report_blob_path': report_blob_path,
                            }
                        )
                    )
                if convert_tables:
                    for table in page_content.get('tables'):
                        table_docs.append(
                            Document(
                                page_content=str(table),
                                metadata={
                                    'text': text_content, 
                                    'pdf_name': pdf_name,
                                    'page_num': page_num,
                                    'company_name': company_name,
                                    'report_quarter': report_quarter,
                                    'page_titles': '',
                                    'page_headers': '',
                                    'section_headers': '',
                                    'page_footers': '',
                                    # 'report_blob_path': report_blob_path,
                                    }
                                )
                            )
                if convert_charts:
                    pass 
            if page_content.get('title') is not None:
                text_docs[-1].metadata['page_titles'] = ', '.join(page_content.get('title'))
                table_docs[-1].metadata['page_titles'] = ', '.join(page_content.get('title'))
            if page_content.get('pageHeader') is not None:
                text_docs[-1].metadata['page_headers'] = ', '.join(page_content.get('pageHeader'))
                table_docs[-1].metadata['page_headers'] = ', '.join(page_content.get('pageHeader'))
            if page_content.get('sectionHeader') is not None:
                text_docs[-1].metadata['section_headers'] = ', '.join(page_content.get('sectionHeader'))
                table_docs[-1].metadata['section_headers'] = ', '.join(page_content.get('sectionHeader'))
            if page_content.get('pageFooter') is not None:
                text_docs[-1].metadata['page_footers'] = ', '.join(page_content.get('pageFooter'))
                table_docs[-1].metadata['page_footers'] = ', '.join(page_content.get('pageFooter'))
        self.logger.info(
            "Created {0} text Documents, {1} table Documents, and {2} chart Documents".format(
                len(text_docs), 
                len(table_docs), 
                len(chart_docs)
            ))
        return text_docs, table_docs, chart_docs
    
    def chunk_docs(self, lang_docs, chunk_size=400):
        """Chunk list of Document objects."""
        text_splitter = TokenTextSplitter(chunk_size=chunk_size, chunk_overlap=0)
        # text_splitter = CharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=0)
        lang_doc_chunks = text_splitter.split_documents(lang_docs)
        self.logger.info("Chunked {0} Documents to {1}".format(
            len(lang_docs), len(lang_doc_chunks))
        )
        return lang_doc_chunks
    
    def get_search_index(
            self, 
            upload_docs=None, 
            upload_docs_in_batches=False,
            batch_size=50,
            overwrite_index=False,
        ):
        """
        Get an Azure AI Search index with an option to upload Documents to it.
        """
        self.logger.info("Getting index '{0}' from AI Search service '{1}'..".\
                        format(
                            self.azure_search_index_name,
                            self.azure_search_service_name,
                        ))
        try:
            self.search_client.get_index(self.azure_search_index_name)
        except:
            self.logger.info(
                "Did not find index '{0}' in service {1}".\
                    format(
                        self.azure_search_index_name, 
                        self.azure_search_service_name
                    ))
            index_exists = 0
        else:
            self.logger.info(
                "Found existing index '{0}' in search service '{1}'".\
                    format(
                        self.azure_search_index_name, 
                        self.azure_search_service_name
                    ))
            index_exists = 1
        finally:
            # default field names see https://python.langchain.com/docs/integrations/vectorstores/azuresearch/
            fields = [
                SimpleField(
                    name="id",
                    type=SearchFieldDataType.String,
                    key=True,
                    filterable=True,
                ),
                SearchableField(
                    name="content",
                    type=SearchFieldDataType.String,
                    searchable=True,
                ),
                SearchField(
                    name="content_vector",
                    type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
                    searchable=True,
                    vector_search_dimensions=len(
                        self.embedding_model.embed_query("Text")
                    ),
                    # vector_search_configuration="default",
                    vector_search_profile_name="finqaHnsw",
                ),
                SearchableField(
                    name="metadata",
                    type=SearchFieldDataType.String,
                    searchable=True,
                    filterable=True,
                ),
                SimpleField(
                    name="company_name",
                    type=SearchFieldDataType.String,
                    filterable=True,
                    searchable=True,
                ),
                SimpleField(
                    name="report_quarter",
                    type=SearchFieldDataType.String,
                    filterable=True,
                    searchable=True,
                ),
                SimpleField(
                    name="page_titles",
                    type=SearchFieldDataType.String,
                    # filterable=True,
                    searchable=True,
                ),
                SimpleField(
                    name="page_headers",
                    type=SearchFieldDataType.String,
                    # filterable=True,
                    searchable=True,
                ),
                SimpleField(
                    name="page_footers",
                    type=SearchFieldDataType.String,
                    # filterable=True,
                    searchable=True,
                ),
                SimpleField(
                    name="section_headers",
                    type=SearchFieldDataType.String,
                    # filterable=True,
                    searchable=True,
                ),
            ]
            vector_search = VectorSearch(
                algorithms=[
                    HnswAlgorithmConfiguration(
                        name="finqaHnsw",
                        kind=VectorSearchAlgorithmKind.HNSW,
                        parameters=HnswParameters(
                            m=4,
                            ef_construction=400,
                            ef_search=500,
                            metric=VectorSearchAlgorithmMetric.COSINE,
                        ),
                    ),
                    # ExhaustiveKnnAlgorithmConfiguration(
                    #     name="default_exhaustive_knn",
                    #     kind=VectorSearchAlgorithmKind.EXHAUSTIVE_KNN,
                    #     parameters=ExhaustiveKnnParameters(
                    #         metric=VectorSearchAlgorithmMetric.COSINE
                    #     ),
                    # ),
                ],
                profiles=[
                    VectorSearchProfile(
                        name="finqaHnsw",
                        algorithm_configuration_name="finqaHnsw",
                    ),
                    # VectorSearchProfile(
                    #     name="myExhaustiveKnnProfile",
                    #     algorithm_configuration_name="default_exhaustive_knn",
                    # ),
                ],
            )
            if overwrite_index:
                if index_exists:
                    self.logger.info("Overwriting index '{0}'".\
                        format(
                            self.azure_search_index_name, 
                            self.azure_search_service_name
                        ))
                    self.search_client.delete_index(self.azure_search_index_name)
                else:
                    self.logger.info("Did not find index to overwrite.")
            ai_search_index = AzureSearch(
                azure_search_endpoint=self.azure_search_endpoint,
                azure_search_key=self.azure_search_key,
                index_name=self.azure_search_index_name,
                embedding_function=self.embedding_model.embed_query,
                fields=fields,
                additional_search_client_options={"retry_total": 4},
                vector_search=vector_search,
            )
            if upload_docs is not None:
                if upload_docs_in_batches:
                    doc_batches = [
                        upload_docs[i:i+batch_size] for i in range(
                            0, len(upload_docs), batch_size)
                        ]
                    for doc_batch in doc_batches:
                        tot_time = time.time()
                        try:
                            batch_time = time.time()
                            self.logger.info("Attempting to upload batch of {0} Documents to index '{1}'..".\
                                format(
                                    len(doc_batch), 
                                    self.azure_search_index_name
                                ))
                            ai_search_index.add_documents(documents=upload_docs)
                            self.logger.info("Successfully uploaded batch of {0} Documents to index '{1}' in {2} seconds".\
                                format(
                                    len(doc_batch), 
                                    self.azure_search_index_name, 
                                    round(time.time() - batch_time)
                                ))
                        except: 
                            self.logger.info("Unable to upload batch of {0} Documents to index '{1}'. Trying again.".\
                                format(
                                    len(doc_batch), 
                                    self.azure_search_index_name, 
                                ))
                        else:
                            self.logger.info("Successfully uploaded a total of {0} Documents to index '{1}' in {2} seconds".\
                                format(
                                    len(doc_batch), 
                                    self.azure_search_index_name, 
                                    round(time.time() - tot_time)
                                ))
                else:
                    self.logger.info("Attempting to upload {0} Documents to index '{1}'..".\
                        format(
                            len(upload_docs), 
                            self.azure_search_index_name
                        ))
                    t = time.time()
                    ai_search_index.add_documents(documents=upload_docs)
                    self.logger.info("Successfully uploaded {0} Documents to index '{1}' in {2} seconds".\
                        format(
                            len(upload_docs), 
                            self.azure_search_index_name, 
                            round(time.time() - t)
                        ))
        return ai_search_index

    def ingest_pdfs(
            self, 
            pdf_file, 
            process_charts=False,
            chart_model='deplot',
            chart_model_path='',
            upload_docs_in_batches=True,
            batch_size=50,
            overwrite_index=False,
        ):
        """
        Parse PDFs, construct and chunk Document objects of PDF contents, 
        and upload Documents to an index.
        """
        result_dicts = parse_pdfs([pdf_file])
        pdf_pages_dict = page_pdf_contents(result_dicts)
        text_docs, table_docs, chart_docs = \
            self.convert_paged_pdf_contents_to_docs(
                pdf_pages_dict,
                convert_charts=process_charts,
            )
        if process_charts:
            self.generate_table_from_chart(
                pdf_pages_dict,
                chart_model=chart_model,
                chart_model_path=chart_model_path
        )
        text_doc_batches = self.chunk_docs(text_docs)
        combined_docs = text_docs + table_docs + chart_docs
        self.get_search_index(
            upload_docs=combined_docs, 
            upload_docs_in_batches=upload_docs_in_batches,
            batch_size=batch_size,
            overwrite_index=overwrite_index,
        )

    def _get_blob_container_client(self):
        """Instantiate Azure Blob Storage container client."""
        self.logger.info(
                "Getting Azure Blob Storage container client '{0}' from account '{1}'".format(
                    self.azure_storage_container_name,
                    self.azure_storage_container_account,
                ))
        blob_service_client = \
            BlobServiceClient.from_connection_string(
                self.azure_storage_connection_string
            )
        container_client = \
            blob_service_client.get_container_client(
                self.azure_storage_container_name
            )
        return container_client

    def _get_search_client(self):
        """Instantiate Azure AI Search client."""
        self.logger.info("Getting Azure AI Search client from service '{0}'..".format(
            self.azure_search_service_name
            ))
        azure_search_endpoint = "https://" + self.azure_search_service_name \
                                    + ".search.windows.net"
        search_client = SearchIndexClient(
            azure_search_endpoint, 
            AzureKeyCredential(self.azure_search_key),
        )
        return search_client

    def _get_embedding_model(self):
        """Instantiate OpenAI embedding model."""
        openai_api_deployment = "text-embedding-3-small"
        self.logger.info(
            "Getting OpenAI embedding model '{0}'..".format(
                openai_api_deployment
            ))
        embeddings = AzureOpenAIEmbeddings(
            deployment=openai_api_deployment,
            azure_endpoint=os.environ['AZURE_ENDPOINT'],
            openai_api_version=os.environ['AZURE_OPENAI_API_VERSION'],
            # openai_api_key=os.environ['OPENAI_API_KEY'],
            # show_progress_bar=True,
            chunk_size = 1
        )
        return embeddings
    
    def _load_api_vars(self):
        self.azure_search_key = os.getenv('AZURE_AI_SEARCH_KEY')
        self.azure_search_index_name = os.getenv('AZURE_AI_SEARCH_INDEX_NAME')
        self.azure_search_service_name = os.getenv('AZURE_AI_SEARCH_SERVICE_NAME')
        self.azure_storage_container_name = os.getenv('AZURE_STORAGE_CONTAINER_NAME')
        self.azure_storage_container_account = os.getenv('AZURE_STORAGE_CONTAINER_ACCOUNT')
        self.azure_storage_connection_string = os.getenv('AZURE_STORAGE_CONNECTION_STRING')
        self.azure_search_endpoint = \
            "https://" + self.azure_search_service_name + ".search.windows.net"
        self.logger.info('Set API variables')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--pdf_file",
        type=str,
        help="PDF file location",
    )
    parser.add_argument(
        "--process_charts",
        type=str,
        help="Whether to process and index extracted chart figures",
        default=False,
    )
    parser.add_argument(
        "--chart_model",
        type=str,
        help="Chart model used to convert the chart to tabular form",
        default='deplot',
    )
    parser.add_argument(
        "--chart_model_path",
        type=str,
        help="Chart model path",
        default='',
    )
    parser.add_argument(
        "--upload_docs_in_batches",
        type=bool,
        help="Whether to upload Documents to index in batches",
        default=True,
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        help="Batch size to use when uploading Documents to index",
        default=50,
    )
    parser.add_argument(
        "--overwrite_index",
        type=bool,
        help="Whether to overwrite index if it exists",
        default=False,
    )
    args = parser.parse_args()
    ingestion_pipeline = IngestionPipeline()
    ingestion_pipeline.ingest_pdfs(
        pdf_file=args.pdf_file, 
        process_charts=args.process_charts,
        chart_model=args.chart_model,
        chart_model_path=args.chart_model_path,
        upload_docs_in_batches=args.upload_docs_in_batches,
        batch_size=args.batch_size,
        overwrite_index=args.overwrite_index,
    )