import os
import sys
import json
import time
import copy
import logging
import argparse

from PIL import Image
from PyPDF2 import PdfReader, PdfWriter
from pdf2image import convert_from_path
from langchain.docstore.document import Document
from langchain_openai import AzureOpenAIEmbeddings, OpenAIEmbeddings
from langchain_community.vectorstores.azuresearch import AzureSearch
from langchain.text_splitter import TokenTextSplitter, CharacterTextSplitter

from transformers import Pix2StructProcessor, Pix2StructForConditionalGeneration
from src.financialqa.ingestion.models.model_base_decoder import infer_base_decoder

from azure.core.credentials import AzureKeyCredential
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient
from azure.search.documents.indexes import SearchIndexClient
from azure.search.documents.indexes.models import (
    SearchableField,
    SearchField,
    SearchFieldDataType,
    SimpleField,
    VectorSearch,
    HnswParameters,
    VectorSearchProfile,
    VectorSearchAlgorithmKind,
    HnswAlgorithmConfiguration,
    VectorSearchAlgorithmMetric,
)

from dotenv import load_dotenv
load_dotenv(override=True)

from .helper import preprocess_text
from .parser import extract_pdf_contents, page_pdf_contents

import warnings  # not recommended, to suppress langchain openai error
warnings.filterwarnings("ignore")

'''
To-do's:
    - Fix loading files from blob storage
'''

class IngestionPipeline:
    """
    Extract and ingest multi-structured PDF contents into a search index.

    Attributes:
        blob_storage_container (ContainerClient): The client for the blob 
            storage container.
        search_client (SearchIndexClient): The client for the Azure AI Search service.
        embedding_model (AzureOpenAIEmbeddings): The model used for generating vector embeddings.
    """
    
    def __init__(self):
        self.configure_logging()
        self._load_api_vars()
        self.blob_storage_container = self._get_blob_container_client()
        self.search_client = self._get_search_client()
        self.embedding_model = self._get_embedding_model()

    def configure_logging(self):
        """
        Configure logging for the ingestion pipeline.

        Returns:
            None
        """
        logger = logging.getLogger(
            'azure.core.pipeline.policies.http_logging_policy'
        )  
        logger.setLevel(logging.CRITICAL)
        httpx_logger = logging.getLogger('httpx')  
        httpx_logger.setLevel(logging.WARNING)  # to suppress Azure INFO logs 
        logging.basicConfig(        
            level=logging.INFO,    
            format="%(asctime)s %(levelname)s %(name)s line %(lineno)d  %(message)s",    
            datefmt="%H:%M:%S",
            force=True,
        )  
        self.logger = logging.getLogger(__name__)  
        self.logger.info("Configured logging")

    def extract_report_contents(self, load_from_local=False):
        """
        Extract blob reports from Azure Blob Storage container.

        Args:
            load_from_local (bool): Whether to load files from local storage.

        Returns:
            dict: Dictionary containing report contents with keys as report 
                names and values as dictionaries with company name, report 
                quarter, and report blob path.
        """
        report_contents = {}
        self.logger.info(
            "Extracting {0} PDF contents from Azure Blob Storage container '{1}'...".\
                format(
                    len(select_files),
                    self.azure_storage_container_name,
                ))
        for blob in self.blob_storage_container.list_blobs():
            if select_files and blob.name not in select_files:
                continue
            report_name = blob.name
            self.logger.info("Extracting contents from file '{0}'.".format(report_name))
            report_blob_path = 'https://' \
                                + os.environ['AZURE_STORAGE_CONTAINER_ACCOUNT'] \
                                + '.blob.core.windows.net/' \
                                + os.environ['AZURE_STORAGE_CONTAINER_NAME'] \
                                + '/' + report_name
            name_contents = report_name.split('_')
            company_name = name_contents[0]
            report_quarter = name_contents[-1].replace('.pdf', '')
            report_contents[report_name] = {
                'company_name': company_name, 
                'report_quarter': report_quarter,
                'report_blob_path': report_blob_path,
            }
        return report_contents
    
    def crop_images_from_pdfs(
            self, 
            pdf_pages_dict, 
            save_as_jpg=False,
        ):
        """
        Crop and save images from PDFs using PyPDF2 based on bounding box 
        coordinates generated by Azure Document Intelligence.

        Args:
            pdf_pages_dict (dict): A dictionary containing extracted PDF contents.
            save_as_jpg (bool): Whether to save cropped images as JPEG.
        
        Returns:
            None
        """
        for pdf_name, pdf_contents in pdf_pages_dict.items():
            pdf_pages = pdf_contents.get('pages')
            for page_num, page_dict in pdf_pages.items():
                if not 'figures' in page_dict:
                    continue
                self.logger.info(
                    f"Processing figures on page {page_num} of '{pdf_name}'..."
                )
                pdf_figures = page_dict.get('figures')
                pdf_file = os.path.join('../data', pdf_name + '.pdf')
                reader = PdfReader(pdf_file)
                page = reader.pages[page_num-1]
                for figure_name, figure_items in pdf_figures.items():
                    bounding_regions_polygon = figure_items.get('bounding_regions_polygon')
                    # found this 72 scaling factor here:
                    # https://github.com/microsoft/Form-Recognizer-Toolkit/blob/main/SampleCode/Python/sample_figure_understanding.ipynb
                    bounding_regions_polygon = [72 * polygon for polygon in bounding_regions_polygon]
                    x1, y1, x2, y2, x3, y3, x4, y4 = bounding_regions_polygon
                    page_mediabox_upper_left = copy.deepcopy(page.mediabox.upper_left)
                    page_mediabox_lower_right = copy.deepcopy(page.mediabox.lower_right)
                    new_upper_left = (
                        page.mediabox.upper_left[0].as_numeric() + x1, 
                        page.mediabox.upper_left[1].as_numeric() - y1
                    )
                    new_upper_right = (
                        page.mediabox.upper_left[0].as_numeric() + x2, 
                        page.mediabox.upper_left[1].as_numeric() - y2
                    )
                    new_lower_right = (
                        page.mediabox.upper_left[0].as_numeric() + x3, 
                        page.mediabox.upper_left[1].as_numeric() - y3
                    )
                    new_lower_left = (
                        page.mediabox.upper_left[0].as_numeric() + x4, 
                        page.mediabox.upper_left[1].as_numeric() - y4
                    )
                    page.mediabox.upper_left = new_upper_left
                    page.mediabox.lower_right = new_lower_right
                    # page.mediabox.upper_right = new_upper_right
                    # page.mediabox.lower_left = new_lower_left
                    writer = PdfWriter() # find a workaround to reinitalizing
                    writer.add_page(page)
                    page.mediabox.upper_left = page_mediabox_upper_left
                    page.mediabox.lower_right = page_mediabox_lower_right
                    output_dir = os.path.join('../data/outputs', pdf_name)
                    if not os.path.isdir(output_dir):
                        os.makedirs(output_dir)
                    pdf_file_path = os.path.join(
                        output_dir, figure_name + '.pdf',
                    )
                    pdf_pages.get(page_num).get('figures').get(figure_name).\
                        update({'pdf_file_path': pdf_file_path})
                    with open(pdf_file_path, 'wb') as out_f:
                        writer.write(out_f)
                        self.logger.info(
                            f"Saving figure '{figure_name}' as PDF to folder {pdf_file_path}"
                        )
                    if save_as_jpg:
                        jpg_output_folder = os.path.join(
                            '../data', 'outputs', pdf_name, 'jpg_outputs',
                        )
                        if not os.path.isdir(jpg_output_folder):   
                            os.makedirs(jpg_output_folder)
                        images = convert_from_path(
                            pdf_file_path,
                            fmt='JPEG',
                            output_folder=jpg_output_folder,
                        )
                        jpg_file_path = os.path.join(
                            jpg_output_folder, 
                            figure_name + '.jpg',
                        )
                        pdf_pages.get(page_num).get('figures').get(figure_name).\
                            update({'jpg_file_path': jpg_file_path})
                        for img in images:
                            self.logger.info(
                                f"Saving figure '{figure_name}' as JPEG to folder {jpg_output_folder}"
                            )
                            img.save(fp=jpg_file_path)

    def generate_chartvlm_output(
            self,
            model_path,
            image_path,
        ):
        """
        Generate ChartVLM output based on model and image path.
        
        Args:
            model_path (str): Path to ChartVLM model.
            image_path (str): Path to image file.
        
        Returns:
            str: ChartVLM output.
        """
        self.logger.info(
            f'Generating ChartVLM output for figure with image path {image_path}...'
        )
        img = Image.open(image_path).convert("RGB")
        chartvlm_decoder_output = infer_base_decoder(
            img, 
            model_path, 
            title_type=False,
        )
        self.logger.info(
            f'ChartVLM output for figure with image path {image_path}:\n{chartvlm_decoder_output}'
        )
        return chartvlm_decoder_output
    
    def generate_deplot_output(
            self, 
            image_path,
        ):
        """
        Generate DePlot output based on image path.
        
        Args:
            image_path (str): Path to image file.
            
        Returns:
            str: DePlot output.
        """
        pix2struct_processor = Pix2StructProcessor.from_pretrained('google/deplot')
        pix2struct_model = Pix2StructForConditionalGeneration.from_pretrained('google/deplot')
        self.logger.info(
            f'Generating DePlot output for figure with image path {image_path}...'
        )
        image = Image.open(fp=image_path)
        inputs = pix2struct_processor(
            images=image, 
            text="Generate underlying data table of the figure below:", 
            return_tensors="pt"
        )
        predictions = pix2struct_model.generate(**inputs, max_new_tokens=512)
        deplot_output = pix2struct_processor.decode(
            predictions[0], 
            skip_special_tokens=True
        )
        self.logger.info(
            f'DePlot output for figure with image path {image_path}:\n{deplot_output}'
        )
        return deplot_output

    def generate_table_from_chart(
            self,
            pdf_pages_dict,
            chart_model='deplot',
            chart_model_path='',
        ):
        """
        Generate linearized table from chart figure using specified model.
        
        Args:
            pdf_pages_dict (dict): A dictionary containing extracted PDF contents.
            chart_model (str): Model to use for converting chart to table.
            chart_model_path (str): Path to chart model.
            
        Returns:
            None
        """
        for pdf_name, pdf_items in pdf_pages_dict.items():
            company_name = pdf_items.get('company_name')
            pages = pdf_items.get('pages')
            for page_num, page_content in pages.items():
                if not 'figures' in page_content.keys():
                    continue
                for figure_name, figure_contents in page_content.get('figures').items():
                    image_path = figure_contents.get('jpg_file_path')
                    if chart_model == 'chartvlm':
                        chart_to_table_output = self.generate_chartvlm_output(
                            chart_model_path,
                            image_path,
                        )
                    elif chart_model == 'deplot':
                        chart_to_table_output = self.generate_deplot_output(
                            image_path,
                        )
                    figure_contents.update({'chart_table': chart_to_table_output})

    def convert_paged_pdf_contents_to_docs(
            self, 
            pdf_pages_dict,
            convert_tables=True,
            convert_charts=True,
        ):
        """
        Create Document objects from extracted PDF contents.

        Args:
            pdf_pages_dict (dict): A dictionary containing extracted PDF contents.
            convert_tables (bool): Whether to convert extracted tables to Document objects.
            convert_charts (bool): Whether to convert extracted charts to Document objects.
        
        Returns:
            tuple: A tuple containing three lists - text_docs, table_docs, and chart_docs.
        """
        text_docs = []
        table_docs = []
        chart_docs = []
        for pdf_name, pdf_items in pdf_pages_dict.items():
            self.logger.info(
                f"Converting extracted '{pdf_name}' contents to Documents..."
            )
            company_name = pdf_items.get('company_name')
            report_quarter = pdf_items.get('report_quarter')
            pages = pdf_items.get('pages')
            for page_num, page_content in pages.items():
                page_titles = ''
                page_headers = ''
                page_footers = ''
                section_headers = ''
                if 'title' in page_content.keys():
                    page_titles = ', '.join(page_content.get('title'))
                if 'sectionHeading' in page_content.keys():
                    section_headers = ', '.join(page_content.get('sectionHeading'))
                if 'pageHeader' in page_content.keys():
                    page_headers = ', '.join(page_content.get('pageHeader'))
                if 'pageFooter' in page_content.keys():
                    page_footers = ', '.join(page_content.get('pageFooter'))
                # Convert text content by default
                text_content = preprocess_text(' '.join(page_content.get('text')))
                text_docs.append(
                    Document(
                        page_content=text_content,
                        metadata={
                            'page_num': page_num,
                            'pdf_name': pdf_name,
                            'company_name': company_name,
                            'report_quarter': report_quarter,
                            'page_titles': page_titles,
                            'page_headers': page_headers,
                            'section_headers': section_headers,
                            'page_footers': page_footers,
                            }
                        )
                    )
                if convert_tables:
                    if not 'tables' in page_content.keys():
                        continue
                    for table in page_content.get('tables'):
                        table_docs.append(
                            Document(
                                page_content=str(table),
                                metadata={
                                    'text': text_content, 
                                    'pdf_name': pdf_name,
                                    'page_num': page_num,
                                    'company_name': company_name,
                                    'report_quarter': report_quarter,
                                    'page_titles': page_titles,
                                    'page_headers': page_headers,
                                    'section_headers': section_headers,
                                    'page_footers': page_footers,
                                    }
                                )
                            )
                if convert_charts:
                    if not 'figures' in page_content.keys():
                        continue
                    for figure_name, figure_contents in page_content.get('figures').items():
                        if 'chart_table' in figure_contents.keys():
                            chart_table = figure_contents.get('chart_table')
                        else:
                            self.logger.info(
                                f"Missing chart table for {figure_name} of '{pdf_name}'")
                            break
                        chart_docs.append(
                            Document(
                                page_content=chart_table.strip(),
                                metadata={
                                    'page_num': page_num,
                                    'pdf_name': pdf_name,
                                    'company_name': company_name,
                                    'report_quarter': report_quarter,
                                    'page_titles': page_titles,
                                    'page_headers': page_headers,
                                    'section_headers': section_headers,
                                    'page_footers': page_footers,
                                    }
                                )
                            )
            self.logger.info(
                "Created {0} text, {1} table, and {2} chart Documents for PDF {3}".format(
                    len(text_docs), 
                    len(table_docs), 
                    len(chart_docs),
                    pdf_name,
                ))
        return text_docs, table_docs, chart_docs
    
    def chunk_docs(self, docs, chunk_size=400):
        """
        Chunk list of Document objects.

        Args:
            docs (list): List of Document objects.
            chunk_size (int): Size of chunks to split Documents into.
        
        Returns:
            list: List of chunked Document objects.
        """
        text_splitter = TokenTextSplitter(chunk_size=chunk_size, chunk_overlap=0)
        # text_splitter = CharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=0)
        doc_chunks = text_splitter.split_documents(docs)
        self.logger.info(
            "Chunked {0} Documents to {1} using a chunk size of {2} ".format(
                len(docs), len(doc_chunks), chunk_size))
        return doc_chunks
    
    def get_search_index(
            self, 
            upload_docs=None, 
            upload_docs_in_batches=False,
            batch_size=50,
            overwrite_index=False,
        ):
        """
        Get an Azure AI Search index with an option to upload Documents to it.

        Args:
            upload_docs (list): List of Document objects to upload to index.
            upload_docs_in_batches (bool): Whether to upload Documents in batches.
            batch_size (int): Number of Documents to upload per batch.
            overwrite_index (bool): Whether to overwrite index if it exists.
        
        Returns:
            ai_search_index (AzureSearch): Azure AI Search index object.
        """
        self.logger.info("Getting index '{0}' from AI Search service '{1}'..".\
                        format(
                            self.azure_search_index_name,
                            self.azure_search_service_name,
                        ))
        try:
            self.search_client.get_index(self.azure_search_index_name)
        except:
            self.logger.info(
                "Did not find index '{0}' in service {1}".\
                    format(
                        self.azure_search_index_name, 
                        self.azure_search_service_name
                    ))
            index_exists = 0
        else:
            self.logger.info(
                "Found existing index '{0}' in search service '{1}'".\
                    format(
                        self.azure_search_index_name, 
                        self.azure_search_service_name
                    ))
            index_exists = 1
        finally:
            # default field names see https://python.langchain.com/docs/integrations/vectorstores/azuresearch/
            fields = [
                SimpleField(
                    name="id",
                    type=SearchFieldDataType.String,
                    key=True,
                    filterable=True,
                ),
                SearchableField(
                    name="content",
                    type=SearchFieldDataType.String,
                    searchable=True,
                ),
                SearchField(
                    name="content_vector",
                    type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
                    searchable=True,
                    vector_search_dimensions=len(
                        self.embedding_model.embed_query("Text")
                    ),
                    # vector_search_configuration="default",
                    vector_search_profile_name="finqaHnsw",
                ),
                SearchableField(
                    name="metadata",
                    type=SearchFieldDataType.String,
                    searchable=True,
                    filterable=True,
                ),
                SimpleField(
                    name="company_name",
                    type=SearchFieldDataType.String,
                    filterable=True,
                    searchable=True,
                ),
                SimpleField(
                    name="report_quarter",
                    type=SearchFieldDataType.String,
                    filterable=True,
                    searchable=True,
                ),
                SimpleField(
                    name="page_titles",
                    type=SearchFieldDataType.String,
                    # filterable=True,
                    searchable=True,
                ),
                SimpleField(
                    name="page_headers",
                    type=SearchFieldDataType.String,
                    # filterable=True,
                    searchable=True,
                ),
                SimpleField(
                    name="page_footers",
                    type=SearchFieldDataType.String,
                    # filterable=True,
                    searchable=True,
                ),
                SimpleField(
                    name="section_headers",
                    type=SearchFieldDataType.String,
                    # filterable=True,
                    searchable=True,
                ),
            ]
            vector_search = VectorSearch(
                algorithms=[
                    HnswAlgorithmConfiguration(
                        name="finqaHnsw",
                        kind=VectorSearchAlgorithmKind.HNSW,
                        parameters=HnswParameters(
                            m=4,
                            ef_construction=400,
                            ef_search=500,
                            metric=VectorSearchAlgorithmMetric.COSINE,
                        ),
                    ),
                    # ExhaustiveKnnAlgorithmConfiguration(
                    #     name="default_exhaustive_knn",
                    #     kind=VectorSearchAlgorithmKind.EXHAUSTIVE_KNN,
                    #     parameters=ExhaustiveKnnParameters(
                    #         metric=VectorSearchAlgorithmMetric.COSINE
                    #     ),
                    # ),
                ],
                profiles=[
                    VectorSearchProfile(
                        name="finqaHnsw",
                        algorithm_configuration_name="finqaHnsw",
                    ),
                    # VectorSearchProfile(
                    #     name="myExhaustiveKnnProfile",
                    #     algorithm_configuration_name="default_exhaustive_knn",
                    # ),
                ],
            )
            if overwrite_index:
                if index_exists:
                    self.logger.info("Overwriting index '{0}'".\
                        format(
                            self.azure_search_index_name, 
                            self.azure_search_service_name
                        ))
                    self.search_client.delete_index(self.azure_search_index_name)
                else:
                    self.logger.info("Did not find index to overwrite.")
            ai_search_index = AzureSearch(
                azure_search_endpoint=self.azure_search_endpoint,
                azure_search_key=self.azure_search_key,
                index_name=self.azure_search_index_name,
                embedding_function=self.embedding_model.embed_query,
                fields=fields,
                additional_search_client_options={"retry_total": 4},
                vector_search=vector_search,
            )
            if upload_docs is not None:
                if upload_docs_in_batches:
                    doc_batches = [
                        upload_docs[i:i+batch_size] for i in range(
                            0, len(upload_docs), batch_size)
                        ]
                    tot_time = time.time()
                    for doc_batch in doc_batches:
                        batch_time = time.time()
                        try:
                            self.logger.info("Attempting to upload batch of {0} Documents to index '{1}'..".\
                                format(
                                    len(doc_batch), 
                                    self.azure_search_index_name
                                ))
                            ai_search_index.add_documents(documents=upload_docs)
                        except: 
                            self.logger.info("Unable to upload batch of {0} Documents to index '{1}'. Trying again.".\
                                format(
                                    len(doc_batch), 
                                    self.azure_search_index_name, 
                                ))
                        else:
                            self.logger.info("Successfully uploaded batch of {0} Documents to index '{1}' in {2} seconds".\
                                format(
                                    len(doc_batch), 
                                    self.azure_search_index_name, 
                                    round(time.time() - batch_time)
                                ))
                    self.logger.info("Successfully uploaded a total of {0} Documents to index '{1}' in {2} seconds".\
                        format(
                            len(upload_docs), 
                            self.azure_search_index_name, 
                            round(time.time() - tot_time)
                        ))
                else:
                    self.logger.info("Attempting to upload {0} Documents to index '{1}'..".\
                        format(
                            len(upload_docs), 
                            self.azure_search_index_name
                        ))
                    t = time.time()
                    ai_search_index.add_documents(documents=upload_docs)
                    self.logger.info("Successfully uploaded {0} Documents to index '{1}' in {2} seconds".\
                        format(
                            len(upload_docs), 
                            self.azure_search_index_name, 
                            round(time.time() - t)
                        ))
        return ai_search_index

    def ingest_pdfs(
            self, 
            pdf_file, 
            process_charts=False,
            chart_model='deplot',
            chart_model_path='',
            upload_docs_in_batches=True,
            batch_size=50,
            overwrite_index=False,
        ):
        """
        Extract PDF contents, construct, chunk and generate embeddings 
        of Document objects of PDF contents, and upload Documents to an index.

        Args:
            pdf_file (str): Path to PDF file.
            process_charts (bool): Whether to process and index extracted chart figures.
            chart_model (str): Model used to convert the chart to tabular form.
            chart_model_path (str): Chart model path.
            upload_docs_in_batches (bool): Whether to upload Documents to index in batches.
            batch_size (int): Number of Documents to upload per batch.
            overwrite_index (bool): Whether to overwrite index if it exists.
            
        Returns:
            None
        """
        result_dicts = extract_pdf_contents([pdf_file])
        pdf_pages_dict = page_pdf_contents(result_dicts)
        text_docs, table_docs, chart_docs = \
            self.convert_paged_pdf_contents_to_docs(
                pdf_pages_dict,
                convert_charts=process_charts,
            )
        if process_charts:
            self.generate_table_from_chart(
                pdf_pages_dict,
                chart_model=chart_model,
                chart_model_path=chart_model_path
        )
        text_doc_batches = self.chunk_docs(text_docs)
        combined_docs = text_docs + table_docs + chart_docs
        self.get_search_index(
            upload_docs=combined_docs, 
            upload_docs_in_batches=upload_docs_in_batches,
            batch_size=batch_size,
            overwrite_index=overwrite_index,
        )

    def _get_blob_container_client(self):
        """
        Instantiate Azure Blob Storage container client.

        Returns:
            ContainerClient: The client for the blob storage container.
        """
        self.logger.info(
                "Getting Azure Blob Storage container client '{0}' from account '{1}'".format(
                    self.azure_storage_container_name,
                    self.azure_storage_container_account,
                ))
        blob_service_client = \
            BlobServiceClient.from_connection_string(
                self.azure_storage_connection_string
            )
        container_client = \
            blob_service_client.get_container_client(
                self.azure_storage_container_name
            )
        return container_client

    def _get_search_client(self):
        """
        Instantiate Azure AI Search client.

        Returns:
            SearchIndexClient: The client for the Azure AI Search service.
        """
        self.logger.info("Getting Azure AI Search client from service '{0}'..".format(
            self.azure_search_service_name
            ))
        azure_search_endpoint = "https://" + self.azure_search_service_name \
                                    + ".search.windows.net"
        search_client = SearchIndexClient(
            azure_search_endpoint, 
            AzureKeyCredential(self.azure_search_key),
        )
        return search_client

    def _get_embedding_model(self):
        """
        Instantiate Azure OpenAI embedding model.

        Returns:
            AzureOpenAIEmbeddings: The model used for generating vector embeddings.
        """
        self.logger.info(
            "Getting OpenAI embedding model '{0}' from endpoint {1}..".format(
                self.azure_openai_embedding_model,
                self.azure_openai_endpoint,
            ))
        embeddings = AzureOpenAIEmbeddings(
            deployment=self.azure_openai_embedding_model,
            azure_endpoint=self.azure_openai_endpoint,
            openai_api_version=self.azure_openai_version,
            openai_api_key=self.azure_openai_key,
        )
        return embeddings
    
    def _load_api_vars(self):
        """
        Load API variables from environment variables.

        Returns:
            None
        """
        self.azure_openai_key = os.getenv('AZURE_OPENAI_KEY')
        self.azure_openai_type = os.getenv('AZURE_OPENAI_TYPE')
        self.azure_openai_version = os.getenv('AZURE_OPENAI_VERSION')
        self.azure_openai_endpoint = os.getenv('AZURE_OPENAI_ENDPOINT')
        self.azure_openai_embedding_model = os.getenv('AZURE_OPENAI_EMBEDDING_MODEL')
        self.azure_search_key = os.getenv('AZURE_AI_SEARCH_KEY')
        self.azure_search_index_name = os.getenv('AZURE_AI_SEARCH_INDEX_NAME')
        self.azure_search_service_name = os.getenv('AZURE_AI_SEARCH_SERVICE_NAME')
        self.azure_storage_container_name = os.getenv('AZURE_STORAGE_CONTAINER_NAME')
        self.azure_storage_container_account = os.getenv('AZURE_STORAGE_CONTAINER_ACCOUNT')
        self.azure_storage_connection_string = os.getenv('AZURE_STORAGE_CONNECTION_STRING')
        self.azure_search_endpoint = "https://" + self.azure_search_service_name + ".search.windows.net"
        self.logger.info("Loaded API variables")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--pdf_file",
        type=str,
        help="PDF file location",
    )
    parser.add_argument(
        "--process_charts",
        type=str,
        help="Whether to process and index extracted chart figures",
        default=False,
    )
    parser.add_argument(
        "--chart_model",
        type=str,
        help="Chart model used to convert the chart to tabular form",
        default='deplot',
    )
    parser.add_argument(
        "--chart_model_path",
        type=str,
        help="Chart model path",
        default='',
    )
    parser.add_argument(
        "--upload_docs_in_batches",
        type=bool,
        help="Whether to upload Documents to index in batches",
        default=True,
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        help="Batch size to use when uploading Documents to index",
        default=50,
    )
    parser.add_argument(
        "--overwrite_index",
        type=bool,
        help="Whether to overwrite index if it exists",
        default=False,
    )
    args = parser.parse_args()
    ingestion_pipeline = IngestionPipeline()
    ingestion_pipeline.ingest_pdfs(
        pdf_file=args.pdf_file, 
        process_charts=args.process_charts,
        chart_model=args.chart_model,
        chart_model_path=args.chart_model_path,
        upload_docs_in_batches=args.upload_docs_in_batches,
        batch_size=args.batch_size,
        overwrite_index=args.overwrite_index,
    )